### PR TITLE
Add Gradient Support

### PR DESCRIPTION
**Pull request by kerimovok**
Here's a sample message for a pull request to add the gradient support feature to the `qrcode.vue` component:

---

#### Summary

This PR introduces gradient support for the `qrcode.vue` component, allowing users to generate QR codes with gradient fills. The enhancement includes new props to configure gradient types and colors, applicable to both SVG and Canvas renderings.

#### Changes

1. **New Props**:
    - `gradient`: Boolean to enable/disable gradient fill.
    - `gradientType`: Type of gradient (`linear` or `radial`).
    - `gradientStartColor`: Start color of the gradient.
    - `gradientEndColor`: End color of the gradient.

2. **SVG Renderer**:
    - Added gradient definitions in the SVG output.
    - Applied gradient fill to the QR code path.

3. **Canvas Renderer**:
    - Created gradient objects using `createLinearGradient` or `createRadialGradient`.
    - Applied gradient fill to the QR code rectangles.

#### Usage Examples

**Without Gradient**:
```vue
<template>
  <qrcode-vue
    :size="size"
    :value="fullUrl"
    :level="level"
    :margin="margin"
    :render-as="renderAs"
    :background="background"
    :foreground="foreground"
  />
</template>

<script>
export default {
  data() {
    return {
      size: 200,
      fullUrl: 'https://example.com',
      level: 'H',
      margin: 4,
      renderAs: 'svg', // or 'canvas'
      background: '#ffffff',
      foreground: '#000000',
    }
  },
}
</script>
```

**With Gradient**:
```vue
<template>
  <qrcode-vue
    :size="size"
    :value="fullUrl"
    :level="level"
    :margin="margin"
    :render-as="renderAs"
    :background="background"
    :gradient="true"
    :gradient-type="gradientType"
    :gradient-start-color="gradientStartColor"
    :gradient-end-color="gradientEndColor"
  />
</template>

<script>
export default {
  data() {
    return {
      size: 200,
      fullUrl: 'https://example.com',
      level: 'H',
      margin: 4,
      renderAs: 'svg', // or 'canvas'
      background: '#ffffff',
      gradient: true,
      gradientType: 'linear', // or 'radial'
      gradientStartColor: '#ff0000', // Start color of the gradient
      gradientEndColor: '#0000ff', // End color of the gradient
    }
  },
}
</script>
```

#### Documentation

Updated the `README.md` to include the new props and usage examples for both plain color and gradient QR codes.

#### Testing

- Verified that the gradient properties work correctly for both SVG and Canvas renderings.
- Ensured backward compatibility with existing usage that does not utilize gradient features.

#### Review

Please review the changes and provide feedback. Looking forward to your comments and suggestions.

Thank you!

### CODE REVIEW

**Comment by kerimovok** [comment]
Only the first 2 commits should be merged.

**Comment by scopewu** [comment]
Thank you for contributing to the implementation of this feature; it seems like a great idea. However, there are several issues with your pull request, including extensive code reformatting, license attribution, and incorrect repository links. We need to revise these elements and consolidate your commits.

**Comment by kerimovok** [comment]
Yes, I changed those for my repository, don't know why they are added here. I thought this repo was not maintained anymore, but I see this is, so we don't need my repo anymore. Thank you for your reply!

**Comment by WuChenDi** [comment]
Hi @scopewu 

I think the extension points of this PR are really good. Recently, I've been looking into related business (as shown in the image), and noticed that they have many different types of QR codes. Therefore, I would like to ask if you would consider merging this PR. I reviewed the changes, and found that most of them were due to different indentations.

> 我觉得这个 PR 的扩展点非常好。最近我在看相关的业务（如图所示），发现他们的二维码种类非常多。因此，想请问是否考虑合并该 PR？我查看了改动点，发现大部分改动是由于缩进不同导致的。

image

**Comment by scopewu** [comment]
Yes, very happy for people to submit PRs as bug fixes or feature enhancements.

Indentation or formatting issues can be confusing and git commits can be hard to read. Maybe try using `git rebase` to organize commits.

非常高兴人们能够提交 PR，作为修复 bug 或者功能增强。

缩进或者格式问题会造成混乱，同时 git 提交信息难以阅读。或许可以尝试使用 `git rebase` 整理 commits。

**Comment by WuChenDi** [comment]
@kerimovok Thank you for your response!

I fully agree with your point. Alternatively, I can help address this issue, but this might not be fair to @kerimovok, as it could reduce or remove his commits, which are an important contribution to the project.

> 我非常认同你的观点。或者，我可以帮忙处理这个问题，不过这样对 @kerimovok 可能不太友好，因为这样会减少或移除他的 commits，而这些是他对项目的重要贡献。

**Comment by kerimovok** [comment]
> @kerimovok Thank you for your response!
> 
> I fully agree with your point. Alternatively, I can help address this issue, but this might not be fair to @kerimovok, as it could reduce or remove his commits, which are an important contribution to the project.
> 
> > 我非常认同你的观点。或者，我可以帮忙处理这个问题，不过这样对 @kerimovok 可能不太友好，因为这样会减少或移除他的 commits，而这些是他对项目的重要贡献。

Hello!

I have no problem with it, most important thing is to have this feature available for everyone, thank you for this project!

**Comment by WuChenDi** [comment]
> > @kerimovok Thank you for your response!
> > I fully agree with your point. Alternatively, I can help address this issue, but this might not be fair to @kerimovok, as it could reduce or remove his commits, which are an important contribution to the project.
> > > 我非常认同你的观点。或者，我可以帮忙处理这个问题，不过这样对 @kerimovok 可能不太友好，因为这样会减少或移除他的 commits，而这些是他对项目的重要贡献。
> 
> Hello!
> 
> I have no problem with it, most important thing is to have this feature available for everyone, thank you for this project!

Hello, Thank you for your understanding and support! We share the same goal: to make this feature accessible to everyone.

**Comment by scopewu** [comment]
Closed and switch to #87.

**Pull request closed without merging**
