### PR TITLE
feat: add gradient fill functionality for QR codes

### PR DESCRIPTION
**Pull request by WuChenDi**
- Introduced gradient-related properties in the QrcodeVue component to allow for customizable QR code appearances.
- Implemented both linear and radial gradient options for enhanced visual appeal.
- Updated the README documentation with examples and instructions for using the gradient features.
- Modified the example project to include controls related to gradient options for user testing and demonstration.

### CODE REVIEW

**Comment by WuChenDi** [comment]
First of all, thanks to @kerimovok  for their contribution! 

These features were developed based on their ideas—I simply organized and submitted the PR for merging into the main branch. For more details, please refer to https://github.com/scopewu/qrcode.vue/pull/78.

**Comment by scopewu** [comment]
Hi,
Some code changes emit an error `Uncaught (in promise) Maximum recursive updates exceeded`. `imageProps.value` is an object type that triggers the `onUpdated` cycle every time it is changed.

**Comment by WuChenDi** [comment]
> Hi, Some code changes emit an error `Uncaught (in promise) Maximum recursive updates exceeded`. `imageProps.value` is an object type that triggers the `onUpdated` cycle every time it is changed.
> 
> ```
> -   let imageProps: { x: number, y: number, width: number, height: number }
> +   const imageProps = ref<{ x: number, y: number, width: number, height: number } | null>(null)
> ```

done

**Comment by scopewu** [comment]
Hi, We need to check the code and make minimal changes, deleting old fields when changing here.
```html
<!-- webpack.html -->
<div class="row mb-3">
  <label class="col-sm-2 col-form-label">Foreground:</label>
  <div class="col-sm-10">
    <input type="color" class="border border-3 rounded" v-model="foreground">
  </div>
</div>
```
Sometimes we need to use named parameter arguments so that it is easy to maintain. Also it seems that there are too many parameters, and we need to support the functionality proposed in issue #80 later. There will be too many parameters, so we may need to refactor the documentation.

> 有时我们需要使用具名参数参数，这样好维护。另外似乎参数有点过多，后面还要支持 issue #80 提出的功能。参数会过多，可能另外需要重构文档。

image

**Comment by scopewu** [comment]
有历史原因，有过滤参数的目的。

**Comment by scopewu** [comment]
If continue to add multiple features, it may cause problems, and performance also needs to be considered.
> 如果继续添加功能，可能会出现问题，同时性能也需要考虑。

**Comment by scopewu** [comment]
I'll continue later tonight.
> 我今晚继续，现在有事。

**Comment by WuChenDi** [comment]
Oh, I’m very sorry. 

This is my first time contributing a PR to this project, and I wasn’t aware of the historical context here. I have now reverted this part of the logic to keep it consistent with the previous version.

**Comment by scopewu** [comment]
This thing is a joy, only in code, nothing else, thanks for putting in the effort. Will merge to master branch if there are no major issues. Thanks again.

**Comment by scopewu** [comment]
This thing is a joy, only in code, nothing else, thanks for putting in the effort. Will merge to master branch if there are no major issues. Thanks again.

**Pull request merged**
