### PR TITLE
feat(docs): add more instructions on vue 3 usage

### PR DESCRIPTION
**Pull request by codymikol**
this explain how to configure projects to handle
template bundling / compilation.

Fixes N/A

### CODE REVIEW

**Comment by codymikol** [comment]
It might also make sense to have different files for vue2 usage vs vue3 usage, I could split them up if that is less cluttered as well.

**Review by scopewu — COMMENTED** [review]
Thank you for the pull request.

**Review by scopewu — CHANGES_REQUESTED** [review]
Will be merged.

**Comment by codymikol** [comment]
no problem, thanks for the repo : )

**Pull request merged**
